#! /bin/bash

echo "Manager installation script."
apt update
apt install -y python3-websockets python3-pandas

echo "Download manager file."
wget https://raw.githubusercontent.com/dcsrps/botnet_sim/master/manager/manager.py
python3 manager.py &

echo "Setting up routes."
