#! /bin/bash

echo "Manager installation script."

echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
echo 1 > /proc/sys/net/ipv6/conf/default/disable_ipv6

if test -f /etc/lsb-release; then
	echo "System ubuntu."
	apt-get -o Acquire::ForceIPv4=true update
	export DEBIAN_FRONTEND=noninteractive
	DEBIAN_FRONTEND=noninteractive
	apt-get -o Acquire::ForceIPv4=true install -y python3-websockets python3-pandas
else
	echo "System not ubuntu."
	pip3 install websockets --user;
	pip3 install panadas --user;
fi

echo "Download manager file."
mkdir /opt/manager/
cd /opt/manager/
curl -X GET https://raw.githubusercontent.com/dcsrps/botnet_sim/master/manager/manager.py > /opt/manager/manager.py
python3 manager.py &

echo "Setting up routes."
