#! /bin/bash

echo "Scanner installation script."

echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
echo 1 > /proc/sys/net/ipv6/conf/default/disable_ipv6

echo "Download scanner file."
tmpdir=/opt/scanner
mkdir $tmpdir
curl -X GET https://raw.githubusercontent.com/dcsrps/botnet_sim/master/scanner/scanner.py > $tmpdir/scanner.py
cd $tmpdir
python3 scanner.py &

echo "Setting up routes."
